In [25]:
'''
Question 1
Write a program that will find all numbers which are divisible by 7 but are not a multiple of 5, between
2000 and 3200 (both included). The numbers obtained should be printed in a list.
'''
result=[]
for i in range(2000,3201) :
    if i%7==0 and i%5!=0 :
        result.append(i)
        
#printing the numbers
for i in result :
    print(i)     

2002
2009
2016
2023
2037
2044
2051
2058
2072
2079
2086
2093
2107
2114
2121
2128
2142
2149
2156
2163
2177
2184
2191
2198
2212
2219
2226
2233
2247
2254
2261
2268
2282
2289
2296
2303
2317
2324
2331
2338
2352
2359
2366
2373
2387
2394
2401
2408
2422
2429
2436
2443
2457
2464
2471
2478
2492
2499
2506
2513
2527
2534
2541
2548
2562
2569
2576
2583
2597
2604
2611
2618
2632
2639
2646
2653
2667
2674
2681
2688
2702
2709
2716
2723
2737
2744
2751
2758
2772
2779
2786
2793
2807
2814
2821
2828
2842
2849
2856
2863
2877
2884
2891
2898
2912
2919
2926
2933
2947
2954
2961
2968
2982
2989
2996
3003
3017
3024
3031
3038
3052
3059
3066
3073
3087
3094
3101
3108
3122
3129
3136
3143
3157
3164
3171
3178
3192
3199


In [26]:
'''
Question 2
Write a program that can compute the factorial of a given number.
'''
#take input from user
while True:
    try:
        num = int(input("Enter a positive integer : "))
        if num>=0:
            break  # Exit the loop if conversion is successful and the integer is positive
    except ValueError:
        print("Invalid input. Please enter a valid number.")
        
#calculate the factoriel
fact=1 
for i in range(1,num+1):
    fact=fact*i
    
#print result
print(f"Factoriel of {num} is : {fact}")


Enter a positive integer : h
Invalid input. Please enter a valid number.
Enter a positive integer : -7
Enter a positive integer : 5
Factoriel of 5 is : 120


In [27]:
'''
Question 3
With a given integer number n, write a program to generate a dictionary that contains (i, i*i) such that is an
integral number between 1 and n (both included). and then the program should print the dictionary. 
'''
#read user input
while True:
    try:
        num = int(input("Enter a strictly positive integer : "))
        if num>0:
            break  # Exit the loop if conversion is successful and the integer is positive
    except ValueError:
        print("Invalid input. Please enter a valid number.")
        
#creact dictionary
dict = {x:x*x for x in range(1,num+1)}

#print dictionary
print("result : ",dict)

Enter a strictly positive integer : 8
result :  {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [28]:
'''
Question 4
Given a non-empty string and an int n, return a new string where the char at index n has been removed. The
value of n will be a valid index of a char in the original string (i.e. n will be in the range 0..len(str)-1
inclusive).
'''
#function 
def missing_char(ch,n):
    #check validity of inputs
    if ch=="":
        return "empty string"
    if n not in range(0,len(ch)):
        return "non valid index"
    #result
    return ch[:n] + ch[n+1:]

#main prg
#read user input
ch = input("enter a non empty string : ")
n = int(input("Enter a valid index : "))

#print result
print("result : ",missing_char(ch,n))


enter a non empty string : kitten
Enter a valid index : 1
result :  ktten


In [16]:
'''
Question 5
Write a NumPy program to convert a NumPy array into a Python list structure.
'''
import numpy as np
x= np.arange(9).reshape(3, 3)

print("Original array elements:")
print(x)
print("Array to list:")
print(x.tolist())


Original array elements:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Array to list:
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [23]:
'''
Question 7
Question: Write a program that calculates and prints the value according to the given formula: Q = Square
root of [(2 * C * D)/H]
The following are the fixed values of C and H: C is 50. H is 30
'''
#initialise
Q=[]
H=30
C=50

#get user iput
D=input("enter a comma-separated integer sequence : ")
D_list=D.split(",")

#calculate Q
for d in D_list:
    Q.append(round(((2*int(d)*C)/H)**0.5))
    
#print result
print("result : ",Q)


enter a comma-separated integer sequence : 100,150,180
result :  [18, 22, 24]
